### ISSUE TITLE
Big error while on 1.20.6

### ISSUE THREAD

**Issue by omegartlx** [IkeVoodoo/Infuse-SMP-Plugin#1]
Hi nice plugin everything works but i get this massive error which freezes the player for 1 - 2 seconds so could you help with it please and thank you!

 Could not pass event PlayerInteractEntityEvent to Infuse-Smp v1.0
java.lang.NullPointerException: Cannot get item id from a null item meta!
        at java.base/java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at infuse-smp-1.0.jar/me.ikevoodoo.spigotcore.items.Item.getItemStackId(Item.java:50) ~[infuse-smp-1.0.jar:?]
        at infuse-smp-1.0.jar/me.ikevoodoo.spigotcore.items.listeners.ItemUseListener.getItem(ItemUseListener.java:101) ~[infuse-smp-1.0.jar:?]
        at infuse-smp-1.0.jar/me.ikevoodoo.spigotcore.items.listeners.ItemUseListener.onPlayerInteractEntity(ItemUseListener.java:60) ~[infuse-smp-1.0.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-2228-7708a4c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.performInteraction(ServerGamePacketListenerImpl.java:2854) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.onInteraction(ServerGamePacketListenerImpl.java:2904) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:138) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2843) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1412) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by IkeVoodoo** [comment]
Can you retry this on Spigot instead of Paper?

**Comment by omegartlx** [comment]
No sorry it would brick my whole server.

**Comment by IkeVoodoo** [comment]
Can you stand up another server? Because this doesn't happen for me on my spigot server.

**Comment by omegartlx** [comment]
Yea it doesn't happen on spigot i think it smt with paper

**Comment by omegartlx** [comment]
> Can you stand up another server? Because this doesn't happen for me on my spigot server.

Do you know why its happening

**Comment by IkeVoodoo** [comment]
Not really, paper is probably messing up item metas
